name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.3'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run server in background
      run: |
        python server.py 51234 &
        sleep 5  # Wait for server to start
    - name: Run client tests
      run: |
        python client.py localhost 51234 client_1.txt
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          *.txt
